# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicstreaming', '0002_music_music_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_name',
            field=models.CharField(default='default', max_length=512),
        ),
    ]
